иконка готова
Alex-T-T/hellen-project pull request #115
Opened 2022-05-17 20:19 UTC by VladymyrBolgov

гконка

2022-05-17 21:26 UTC, KateSkoryna requested changes

2022-05-17 21:26 UTC, KateSkoryna commented on src/sass/layout/_about.scss
> +        @media screen and (min-width: 768px){
убрать эту медиа, маджин 10пикселей останется с мобильного и станет 34 с 1680 экрана

2022-05-18 07:31 UTC, KateSkoryna approved these changes

2022-05-18 08:21 UTC, Alex-T-T approved these changes

2022-05-18 08:21 UTC, merged