add position of images and fix some bugs
Alex-T-T/hellen-project pull request #54
Opened 2022-05-14 15:23 UTC by aleksei-v

add adaptaion of images and fix some bugs, almost final version

2022-05-14 16:17 UTC, KateSkoryna reviewed
ФЛЕКСЫЫЫЫЫ

2022-05-14 16:17 UTC, KateSkoryna commented on src/partials/our-program.html
>          srcset="./images/lesson-desktop.webp 1x, ./images/lesson-desktop@2x.webp 2x"
точку убрать из пути

2022-05-14 16:17 UTC, KateSkoryna commented on src/partials/our-program.html
>          srcset="./images/lesson-mobile.jpg 1x, ./images/lesson-mobile@2x.jpg 2x"
точку!

2022-05-14 16:17 UTC, KateSkoryna commented on src/partials/our-program.html
> +      <img class="program__picture" src="./images/lesson-desktop.jpg" alt="English lesson" />
точку

2022-05-14 16:17 UTC, KateSkoryna commented on src/sass/layout/_our-program.scss
> +    line-height: 0;
это к чему нулевой лайн-хайт?

2022-05-14 16:17 UTC, KateSkoryna commented on src/sass/layout/_our-program.scss
>      top: -6px;
задай левый падинг и поставь в левый верхний угол

2022-05-14 16:17 UTC, KateSkoryna commented on src/sass/layout/_our-program.scss
>      transform: rotate(90deg);
а что это ты отротейтил тут)

2022-05-14 16:17 UTC, KateSkoryna commented on src/sass/layout/_our-program.scss
>      min-width: 12px;
просто width

2022-05-14 16:17 UTC, KateSkoryna commented on src/sass/layout/_our-program.scss
>  @media screen and (max-width: 1679px) {
если это повторяется на всех устройствах, выноси в самое начало без медиа, но у тебя на десктопе нет margin-bottom.
479.98
767.98
1679.98

2022-05-14 16:17 UTC, KateSkoryna commented on src/sass/layout/_our-program.scss
> +@media screen and (max-width: 767px) {
767.98

2022-05-14 16:17 UTC, KateSkoryna commented on src/sass/layout/_our-program.scss
> +    .program__term::before {
тут будем думать, выглядит ужасно некрасиво

2022-05-14 16:17 UTC, KateSkoryna commented on src/sass/layout/_our-program.scss
>      .program__container {
там нет падингов, но есть флексы начиная с 768

2022-05-15 06:17 UTC, Alex-T-T requested changes
виправлення та зміни по коментарям готові ?

2022-05-15 07:38 UTC, Alex-T-T approved these changes

2022-05-15 07:38 UTC, merged