Html review
Alex-T-T/hellen-project pull request #55
Opened 2022-05-14 17:52 UTC by Gaydashleo

2022-05-14 21:10 UTC, Alex-T-T commented on src/partials/reviews.html
>      src="/images/review-img/desktop-review1-img.png"
де це зображення, додавай одразу бо буде біда

2022-05-14 21:12 UTC, Alex-T-T commented on src/partials/reviews.html
> +        src="/images/review-img/desktop-review2-img.png"
теж саме

2022-05-14 21:12 UTC, Alex-T-T requested changes
пододавай одразу зображення

2022-05-15 05:13 UTC, Gaydashleo commented on src/partials/reviews.html
>      src="/images/review-img/desktop-review1-img.png"
Ці зображення в папці  image/review-img

2022-05-15 05:54 UTC, Alex-T-T approved these changes

2022-05-15 05:54 UTC, merged