feature/benefits-css-1
Alex-T-T/hellen-project pull request #89
Opened 2022-05-16 19:16 UTC by Yurii2710

scss - section benefits

2022-05-16 20:01 UTC, KateSkoryna requested changes

2022-05-17 10:16 UTC, Alex-T-T approved these changes

2022-05-17 11:56 UTC, KateSkoryna approved these changes

2022-05-17 11:56 UTC, KateSkoryna commented on src/sass/layout/_benefits.scss
> +    padding: 20px 20px 20px 20px;
padding: 20px;
чуть проще сделай

2022-05-17 12:20 UTC, merged